[workspace]
authors = ["jwru <jiawei.ru@qq.com>"]
channels = ["conda-forge"]
name = "Cream"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"

[pypi-dependencies]
soundfile = ">=0.13.1, <0.14"
librosa = ">=0.11.0, <0.12"
loguru = ">=0.7.3, <0.8"
typer = ">=0.17.4, <0.18"
rich = ">=14.1.0, <15"
pytest = ">=8.3.2, <9"
